#SPDX-License-Identifier: MIT-0
---
# tasks file for common
- name: Install common Packages
  become: true
  package:
    name:
      - httpd
      - nodejs
      - npm


- name : Start and enable apache service
  become: true
  service:
    name: httpd
    state: started
    enabled: true

- name: Copy Source Code
  become: true
  synchronize: 
    src: "{{ playbook_dir }}/../../"
    dest: "/opt/todo-app"
    delete: yes
    recursive: yes
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=.github"
      - "--exclude=ansible"
      - "--exclude=todo-frontend"
      - "--exclude=terraform"
      
