#SPDX-License-Identifier: MIT-0
---
# tasks file for ec2_launch
- name: Configure Security Group
  amazon.aws.ec2_group:
    name: vishal-security
    description: "Allow SSH and application access"
    region: "{{ aws_regions }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "0.0.0.0/0"
  register: security_group

- name: Debug Security Group ID
  debug:
    var: security_group.group_id




- name: Provision EC2 instance
  amazon.aws.ec2_instance:
    name: Ansible-create-ec2
    key_name: "{{ ec2_key_name }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_ami_id }}"

    
- name: Debug EC2 AMI ID
  debug:
    var: ec2_ami_id


    wait: yes
    region: "{{ aws_regions }}"
    count: 1
    group_id: "{{ security_group_id }}"
  register: ec2_instance