#SPDX-License-Identifier: MIT-0
---
# tasks file for ec2_launch
- name: Configure Security Group
  amazon.aws.ec2_group:
    name: vishal-security
    description: "Allow SSH and application access"
    region: "{{ aws_regions }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "0.0.0.0/0"
      
      - proto: tcp
        from_port: 3000
        to_port: 3000
        cidr_ip: "0.0.0.0/0"
  register: security_group

- name: Debug Security Group ID
  debug:
    var: security_group.group_id

- name: Provision EC2 instance
  amazon.aws.ec2_instance:
    name: Ansible-create-ec2  #name of ec2 instance
    key_name: "{{ ec2_key_name }}"
    instance_type: "{{ ec2_instance_type }}"
    image_id: ami-0f1dcc636b69a6438
    wait: yes
    region: "{{ aws_regions }}"
    count: 1
    security_group: "{{ security_group.group_id }}"
  register: ec2_instance

- name: Waiting for instance to be ready
  wait_for: 
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 30 
    timeout: 300
    state: started
  loop: "{{ all_instances }}"

- name: Add the Ec2 instance to the inventory dynamically
  add_host: 
    name: "{{ item.public_dns_name }}"
    groups: launched_ec2_instances
    ansible_ssh_private_key_file: "{{ ec2_ssh_key_path }}"
    ansible_user: "{{ ec2_ssh_user }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  loop: "{{ all_instances }}"


- name: Debug SSH Key Path
  debug: 
    var: ec2_ssh_key_path

- name: Debug dynamic inventory
  debug: 
    msg: "All Instances: {{ groups['launched_ec2_instances'] }}"




