# SPDX-License-Identifier: MIT-0
---
# tasks file for ec2_launch

- name: Configure Security Group
  amazon.aws.ec2_group:
    name: vishal-security
    description: "Allow SSH and application access"
    region: "{{ aws_regions }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "0.0.0.0/0"
      - proto: tcp
        from_port: 3000
        to_port: 3000
        cidr_ip: "0.0.0.0/0"
  register: security_group

- name: Debug Security Group ID
  debug:
    var: security_group.group_id

- name: Provision EC2 instance
  amazon.aws.ec2_instance:
    name: Ansible-create-ec2
    key_name: "{{ ec2_key_name }}"
    instance_type: "{{ ec2_instance_type }}"
    image_id: ami-0f1dcc636b69a6438
    wait: yes
    region: "{{ aws_regions }}"
    count: 1
    security_group: "{{ security_group.group_id }}"
  register: ec2_instance

- name: Wait for the instance to be launched
  wait_for:
    host: "{{ ec2_instance.instances[0].public_dns_name }}"
    port: 22
    delay: 30
    timeout: 300
    state: started
  when: ec2_instance.instances is defined and ec2_instance.instances | length > 0

- name: Add EC2 instance to dynamic inventory group
  add_host:
    name: "{{ ec2_instance.instances[0].public_dns_name }}"
    groups: launched_ec2_instances
    ansible_ssh_private_key_file: "~/.ssh/fast-api.pem"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_user: ec2-user


- name: Debug SSH Key Path
  debug:
    var: ec2_ssh_key_path

- name: Debug dynamic inventory
  debug:
    msg: "All Instances: {{ groups['dynamic_hosts'] }}"
