---
- name: Provision EC2 instance & open required ports
  hosts: localhost
  gather_facts: false
  roles:
    - ec2_launch

    
- name: Configuration of Ec2 Instances
  hosts: launched_ec2_instances
  gather_facts: true
  roles:
    - common
    