#SPDX-License-Identifier: MIT-0
---
# tasks file for frontend
- name: Install frontend dependencies
  become: true
  npm:
    path: /opt/todo_app/todo-frontend
    state: present

- name: Build frontend
  become: true
  command: npm run build
  args:
    chdir: /opt/todo_app/todo-frontend